# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

code_task:
  description: >
    You are helping writing python code. These are the instructions:
    
    Instructions ------------ {code_instructions}


  expected_output: >
    Your Final answer must be the full python code, only the python code and nothing else.


evaluate_task:
  description: >
    You are helping writing python code. These are the instructions:
    
    Instructions ------------ {code_instructions}
    
    You will look over the code to insure that it is complete and does the job that it is supposed to do. You will also check for logic error, syntax errors, missing imports, variable declarations, mismatched brackets and missing test cases. If you find any issue in the code, ask the Senior Software Engineer to fix it by providing them the code and the instructions. Don't fix it yourself.


  expected_output: >
    Your Final answer must be the full python code, only the python code and nothing else.

